# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af7609c6a5f897024f265b8573cf28da108833838efe2981bbaa865be3c4a76f3ec2b698bda3db776d0ceb56d30f000f95bc4dd3df81e4b2e9ca6441e9ca0b80

test:
  secret_key_base: 8757f0eb21856f18bffdcbefec2e46ea1b0d8ce58c10089235838f4f47b12499e7aebf148769f7edb2925b50a1e872ebe5814cabe48771eb7fdff1f707ff2e05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
